### ISSUE TITLE
Can't send to HTTPS?

### ISSUE THREAD

**Issue by edalzell** [kissifrot/php-ixr#1]
I'm getting a 301 error when I call an https endpoint. My guess is because you hardcode the port??

**Comment by edalzell** [comment]
Even when you embed the port in the call (which you shouldn't have to), there's an error. Here's my code:
```
		$client = new Client("https://api.webfaction.com:443");
		
		$session = $client->query("login", "foo", "bar");
```

That code should return 
```
<?xml version='1.0'?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value>
            <int>1</int>
          </value>
        </member>
        <member>
          <name>faultString</name>
          <value>
            <string>&lt;class 'webfaction_api.exceptions.LoginError'&gt;:</string>
          </value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>
```

**Comment by kissifrot** [comment]
What is the error exactly ?

**Comment by edalzell** [comment]
I can't remember, sorry...it was a 301. I switched to a different library that didn't have this issue. I though I looked at the code and the `http` was hard coded in there along with the wrong port.

**Comment by kissifrot** [comment]
Well HTTP 301 is a redirect, and this lib doesn't support it.
However you were right about the hardcoded port

**Comment by edalzell** [comment]
You can always try the code above and see what happens. You don't need an account to run that line.

**Comment by kissifrot** [comment]
To make it work better with SSL you should use ClientSSL:
```php
$client = new ClientSSL("https://api.webfaction.com:443");
$session = $client->query("login", "foo", "bar");
```

And in version 1.8.2 you can use
```php
if (false == $session) {
   $xmlError = $client->getError()->getXml();
}
```
to get the response you wanted

**Comment by edalzell** [comment]
Thanks!

**Comment by kissifrot** [comment]
No problem, don't hesitate to create issues if needed :)
