### ISSUE TITLE
Is there any documentation? 

### ISSUE THREAD

**Issue by K2ouMais** [kissifrot/php-ixr#3]
Hello everyone,

is there any documentation for this package? The links seem to be dead.

I installed the package via composer:

```bash
composer require --dev kissifrot/php-ixr
```

I am trying to use this package in Laravel like this:

```php
// Open IXR Client
$ixrClient = new Client(config('lei.vat_validation.vat_provider'));

// Make IXR Query
$ixrQuery = $ixrClient->query('evatrRPC', config('lei.vat_validation.wm_vat'), $this->vatID, $this->company, $this->city, $this->zip, $this->street, $this->print);
```

And I am getting a transport error message.

```
IXR\Message\Error {#294 ▼
  +code: -32300
  +message: "transport error - could not open socket"
}
```

The service I want to get data from is:
https://evatr.bff-online.de/eVatR/xmlrpc/http

It is a service to get a qualified VAT-ID check.

Thank you for the help in advance.

**Comment by tenzap** [comment]
Maybe you have more chance here
https://web.archive.org/web/20160115201135/http://scripts.incutio.com/xmlrpc/
