### ISSUE TITLE
Deprecated creation of dynamic property on PHP 8.2

### ISSUE THREAD

**Issue by dregad** [kissifrot/php-ixr#7]
Seen in DokuWiki's [PHPUnit logs](https://github.com/dokuwiki/dokuwiki/actions/runs/4628595855/jobs/8187868160?pr=3944#step:7:36):

PHP Deprecated:  Creation of dynamic property IXR\Message\Message::$currentTag is deprecated in /home/runner/work/dokuwiki/dokuwiki/vendor/kissifrot/php-ixr/src/Message/Message.php on line 105

https://github.com/kissifrot/php-ixr/blob/3f477ba1e8eeb05c0bfa61463628c73e7c1e3dc0/src/Message/Message.php#L105

There is an existing `_currentTag` property, so maybe it's just a typo (missing `_`) ?
https://github.com/kissifrot/php-ixr/blob/3f477ba1e8eeb05c0bfa61463628c73e7c1e3dc0/src/Message/Message.php#L22

**Comment by kissifrot** [comment]
Thanks for the report, I will ll look into it

**Comment by dregad** [comment]
Thanks for the fix. Don't know if it's intentional, but it's not mentioned on the release notes.
